# Generated by Django 5.0.6 on 2026-05-09 20:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0004_alter_submission_options_submission_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'Cplusplus'), ('JavaScript', 'Javascript'), ('Ruby', 'Ruby'), ('Swift', 'Swift'), ('Go', 'Go'), ('Rust', 'Rust'), ('PHP', 'Php'), ('C#', 'Csharp')], max_length=64, verbose_name='Язык')),
                ('topic', models.CharField(max_length=256, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тема вопросов',
                'verbose_name_plural': 'Темы вопросов',
                'db_table': 'question_topic',
                'unique_together': {('language', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Вопрос')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('answer', models.TextField(verbose_name='Эталонный ответ')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.questiontopic')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
                'unique_together': {('title', 'company')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalQuestion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Вопрос')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('answer', models.TextField(verbose_name='Эталонный ответ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='interview.questiontopic')),
            ],
            options={
                'verbose_name': 'historical Вопрос',
                'verbose_name_plural': 'historical Вопросы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StudentInterviewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solved_questions', models.ManyToManyField(blank=True, related_name='solved_by', to='interview.question', verbose_name='Решённые вопросы')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_profile', to='bot.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Профиль тренажёра',
                'verbose_name_plural': 'Профили тренажёра',
            },
        ),
    ]
