# Generated by Django 5.0.6 on 2026-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('group', models.CharField(choices=[('cpp', 'C++'), ('python', 'Python'), ('rust', 'Rust'), ('blockchain', 'Blockchain')], default='python', max_length=20, verbose_name='Группа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['-created_at'],
            },
        ),
    ]
