# Generated by Django 5.0.6 on 2026-05-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('python', 'Python'), ('rust', 'Rust'), ('blockchain', 'Blockchain')], max_length=20, null=True, verbose_name='Группа'),
        ),
    ]
