# Generated by Django 5.0.6 on 2026-05-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('due_at', models.DateTimeField(verbose_name='Срок сдачи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Дедлайн',
                'verbose_name_plural': 'Дедлайны',
                'ordering': ['-due_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает выполнения'), ('submitted', 'Отправлен на проверку'), ('approved', 'Принят'), ('rejected', 'Отклонён, нужна доработка'), ('overdue', 'Просрочен')], default='pending', max_length=20)),
                ('overdue_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bot.deadline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bot.student')),
            ],
            options={
                'verbose_name': 'Назначение дедлайна',
                'verbose_name_plural': 'Назначения дедлайнов',
                'unique_together': {('deadline', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram file_id')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('document', 'Документ'), ('photo', 'Фото')], default='text', max_length=20)),
                ('mentor_comment', models.TextField(blank=True, verbose_name='Комментарий ментора (при reject)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bot.deadlineassignment')),
            ],
            options={
                'verbose_name': 'Ответ на дедлайн',
                'verbose_name_plural': 'Ответы на дедлайны',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
