# Generated by Django 5.0.6 on 2026-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_deadline_deadlineassignment_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['submitted_at'], 'verbose_name': 'Сообщение в треде', 'verbose_name_plural': 'Сообщения в тредах'},
        ),
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.CharField(choices=[('student', 'Ученик'), ('mentor', 'Ментор')], default='student', max_length=10, verbose_name='Автор сообщения'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='mentor_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий ментора (legacy, при reject)'),
        ),
    ]
